version: 2.1

executors:
   app-executor:
     docker:
       - image: cimg/node:17.7.2
     working_directory: ~/repo
aliases:
  - &show-current-branch
      run:
        name: show current branch
        command: echo $CIRCLE_BRANCH
  - &restore-cache
       restore_cache:
             keys: 
               - app-{{checksum "package.json"}}
               - app-
  - &install-dependencies
       run:
         name: install dependencies
         command: npm install
  - &save-cache
     save_cache:
          paths:
            - node_modules
          key:  app-{{checksum "package.json"}}

  - &installing-awscliv2
       run:
        name: Installing AWS CLI version 2.x
        working_directory: /
        command: |
             sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
             sudo unzip awscliv2.zip 
             sudo ./aws/install
             sudo rm -rf awscliv2.zip
             sudo rm -rf aws
             aws --version
  - &build-app
       run:
         name: Building the application
         command: |
              npm install
              npm run build
              cd build
              zip ../build.zip -r * .[^.]*
              echo "Build successful"



jobs:
  build:
    executor: app-executor  
    steps:
      - checkout
      - run:
          name: show code
          command: cd ~/repo && ls -ltra
      - *show-current-branch
      - *install-dependencies
      - *restore-cache
      - *save-cache

  deploy-to-aws-s3:
    executor: app-executor
    steps:
      - checkout
      - *show-current-branch
      - *installing-awscliv2
      - *build-app
  
      - run:
          name: Deploy to AWS S3
          command: |
            if ["$CIRCLE_BRANCH" == "main"] then
              aws --region $AWS_REGION s3 sync ~/repo/build s3://$PROD_BUCKET --delete
            elif ["$CIRCLE_BRANCH" == "staging"] then
              aws --region $AWS_REGION s3 sync ~/repo/build s3://$STAGE_BUCKET --delete
            elif ["$CIRCLE_BRANCH" == "dev"] then
              aws --region $AWS_REGION s3 sync ~/repo/build s3://$DEV_BUCKET --delete
            else
              echo "No branch found"
            fi
workflows:
  deploy-to-aws-s3:
    jobs:
      - build
      - deploy-to-aws-s3:
           requires:
             - build
             
      
    
        