version: 2.1

executors:
   app-executor:
     docker:
       - image: cimg/node:17.7.2
     working_directory: ~/repo
     
commands:
  show-current-branch:
    description: "Show current branch"
    steps:
      - run:
          name: show current branch
          command: echo $CIRCLE_BRANCH
  restore-cache:
    description: "Restore cache"
    steps:
      - restore_cache:
             keys: 
               - app-{{checksum "package.json"}}
               - app-
  install-dependencies:
    description: "Install dependencies"
    steps:
      - run:
         name: install dependencies
         command: npm install
  save-cache:
    description: "Save cache"
    steps:
      - save_cache:
          paths:
            - node_modules
          key:  app-{{checksum "package.json"}}

  installing-awscliv2:
    description: "Installing awscliv2"
    steps:
      - run:
         name: Installing AWS CLI version 2.x
         working_directory: /
         command: |
             sudo curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" 
             sudo unzip awscliv2.zip 
             sudo ./aws/install
             sudo rm -rf awscliv2.zip
             sudo rm -rf aws
             aws --version
  build-app:
    description: "Build app"
    steps:
      - run:
         name: Building the application
         command: |
              npm install
              npm run build
              cd build
              zip ../build.zip -r * .[^.]*
              echo "Build successful"



jobs:
  create-infrasctructure:
    executor: app-executor
    steps:
      - checkout
      - installing-awscliv2
      - run:
          name: set env variables and create s3 buckets, and  iam users 
          command: |
            export S3_TEMPLATE_POLICY_NAME="s3bucketpolicy"
            export S3_TEMPLATE_BUCKET_NAME="s3buckets"
            export IAM_TEMPLATE_NAME="iam"
            source ~/.bashrc
            echo $S3_TEMPLATE_POLICY_NAME
            echo $S3_TEMPLATE_BUCKET_NAME
            echo $IAM_TEMPLATE_NAME
            cd ~/repo/cf
            sudo chmod +x ./create-s3-bucket.sh
            ./create-s3-bucket.sh
            echo "S3 bucket created"


      
  run-tests:
    description: "Run tests"
    executor: app-executor
    steps:
      - checkout
      - show-current-branch
      - install-dependencies
      - restore-cache
      - save-cache
      - run:
          name: Run tests
          command: |
            cd ~/repo
            npm run test
            echo "Tests successful"
  build:
    executor: app-executor  
    steps:
      - checkout
      - run:
          name: show code
          command: cd ~/repo && ls -ltra && git status
      - show-current-branch
      - install-dependencies
      - restore-cache
      - save-cache

  deploy-to-aws-s3:
    executor: app-executor
    steps:
      - checkout
      - show-current-branch
      - installing-awscliv2
      - build-app
  
      - run:
          name: Deploy to AWS S3
          command: |
            case $CIRCLE_BRANCH in
              main)
               aws --region $AWS_REGION s3 sync ~/repo/build s3://$PROD_BUCKET --delete
                ;;
              stage)
                aws --region $AWS_REGION s3 sync ~/repo/build s3://$STAGE_BUCKET --delete
                  ;;
               dev)
                aws --region $AWS_REGION s3 sync ~/repo/build s3://$DEV_BUCKET --delete
                  ;;
              *)
                echo "No bucket found for branch $CIRCLE_BRANCH"
                ;;
            esac
workflows:
  deploy-to-aws-s3:
    jobs:
      - create-infrasctructure
      - run-tests:
          requires: 
            - create-infrasctructure
      - build:
          requires: 
            - run-tests
      - deploy-to-aws-s3:
           requires:
             - run-tests
             - build
             
      
    
        