AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an Iam user and adds it to the Iam group"

Mappings:
  UserAndGroupRegionMap:
    user: 
       name: circleci-user
    group: 
        name: circleci

    
Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !FindInMap [UserAndGroupRegionMap,  group, name]
      UserName: !FindInMap [UserAndGroupRegionMap, user, name]

  circleci:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !FindInMap [UserAndGroupRegionMap, group, name]
  addUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !FindInMap [UserAndGroupRegionMap, group, name]
      Users:
        - Ref: IamUser