AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an Iam user and adds it to the Iam group"

Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - circleci  
      UserName: circleci-user

  circleci:
    Type: AWS::IAM::Group
    Properties:
      GroupName: circleci
  addUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: circleci
      Users:
        - Ref: IamUser