AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates an Iam user and adds it to the Iam group"

Mappings:
  UserName:
    user: 
      name: circleci-user
  Group: 
    group: 
      name: circleci

    
Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties:
      Groups:
        - !Ref Group
      UserName: !FindInMap [UserName, user, name]

  circleci:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !FindInMap [Group, group, name]
  addUserToGroup:
    Type: AWS::IAM::UserToGroupAddition
    Properties:
      GroupName: !FindInMap [Group, group, name]
      Users:
        - Ref: IamUser