AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates three s3 buckets, prod,stage, and dev"


Mappings:
  BucketNames:
    prod: prod-rayan147-bucket
    stage: stage-rayan147-bucket
    dev: dev-rayan147-bucket


Resources:
  ProdS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !FindInMap [BucketNames, prod, BucketNames.prod]
      AccessControl: "PublicRead"
      VersioningConfiguration: 
        Status: "Enabled"
      WebsiteConfiguration:
            IndexDocument: "index.html"
            ErrorDocument: "error.html"
        
  StageS3:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !FindInMap [BucketNames, stage, BucketNames.stage]
      AccessControl: "PublicRead"
      VersioningConfiguration: 
        Status: "Enabled"
      WebsiteConfiguration:
           IndexDocument: "index.html"
           ErrorDocument: "error.html"
      
  DevS3:
     Type: "AWS::S3::Bucket"
     Properties:
       BucketName: !FindInMap [BucketNames, dev, BucketNames.dev]
       AccessControl: "PublicRead"
       VersioningConfiguration: 
            Status: "Enabled"
       WebsiteConfiguration:
            IndexDocument: "index.html"
            ErrorDocument: "error.html"
  