AWSTemplateFormatVersion: "2010-09-09"
Description:  "Allow s3:GetObject permission for all objects in the bucket"

Mappings:
  BucketNames:
    prod: prod-rayan147-bucket
    stage: stage-rayan147-bucket
    dev: dev-rayan147-bucket

Resources:
  S3BucketPermissionProd:
    Type: "AWS::S3::BucketPolicy"
    Properties:
        Bucket: !FindInMap [BucketNames, prod, BucketNames.prod]
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
              - "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Resource:
              - "arn:aws:s3:::prod-rayan147-bucket/*"
   
  S3BucketPermissionStage:
    Type: "AWS::S3::BucketPolicy"
    Properties:
        Bucket: !FindInMap [BucketNames, stage, BucketNames.stage]
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Resource:
            - "arn:aws:s3:::stage-rayan147-bucket/*"
  S3BucketPermissionDev:
    Type: "AWS::S3::BucketPolicy"
    Properties:
        Bucket: !FindInMap [BucketNames, dev, BucketNames.dev]
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action:
            - "s3:GetObject"
            Effect: "Allow"
            Principal: "*"
            Resource:
            - "arn:aws:s3:::dev-rayan147-bucket/*"
